from __future__ import annotations
from typing import Protocol
from di_contracts.core.models import CanonicalObject, CanonicalRef, CanonicalRevision, ExactObjectRef, LogicalObjectRef, ObjectRef
from di_contracts.core.types import LogicalId, ObjectType
from di_contracts.registry.models import ObjectRegistryEntry

class CanonicalObjectStore(Protocol):
    def put_new(self, obj: CanonicalObject) -> ObjectRef: ...
    def put_revision(self, *, logical_id: LogicalId, expected_parent_refs: tuple[ExactObjectRef, ...], new_object: CanonicalRevision) -> ExactObjectRef: ...
    def get_exact(self, ref: CanonicalRef) -> CanonicalObject: ...
    def list_revisions(self, *, object_type: ObjectType, logical_id: LogicalId) -> tuple[ExactObjectRef, ...]: ...

class ObjectRegistry(Protocol):
    def require(self, object_type: str) -> ObjectRegistryEntry: ...
    def validate_reference_kind(self, ref: CanonicalRef) -> None: ...
    def validate_intervention_target(self, ref: CanonicalRef) -> None: ...
