"""Frozen vocabularies for the ARSO P0.1 experimental harness."""

from enum import StrEnum


class DiagnosisConditionType(StrEnum):
    ORACLE = "ORACLE"
    WRONG = "WRONG"
    NONE = "NONE"
    IMPLICIT = "IMPLICIT"


class ExecutionState(StrEnum):
    CREATED = "CREATED"
    LOCK_VERIFIED = "LOCK_VERIFIED"
    FIXTURE_RESOLVED = "FIXTURE_RESOLVED"
    ASSIGNED = "ASSIGNED"
    INPUT_MATERIALIZED = "INPUT_MATERIALIZED"
    REPAIR_RUNNING = "REPAIR_RUNNING"
    REPAIR_RETURNED = "REPAIR_RETURNED"
    CANDIDATE_MATERIALIZED = "CANDIDATE_MATERIALIZED"
    EVALUATION_RUNNING = "EVALUATION_RUNNING"
    EVALUATED = "EVALUATED"
    VALIDATION_RUNNING = "VALIDATION_RUNNING"
    FINALIZED = "FINALIZED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    CANCELLED = "CANCELLED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"


class ValidationState(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class ScientificAdmissionState(StrEnum):
    PENDING = "PENDING"
    INTEGRITY_CHECKING = "INTEGRITY_CHECKING"
    ADMITTED = "ADMITTED"
    EXCLUDED_PREDEFINED = "EXCLUDED_PREDEFINED"
    INVALID_CONTAMINATION = "INVALID_CONTAMINATION"
    INCOMPLETE = "INCOMPLETE"


class IntegrityStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    INCOMPLETE = "INCOMPLETE"


class SealedAccessPurpose(StrEnum):
    ORACLE_DIAGNOSIS_MATERIALIZATION = "ORACLE_DIAGNOSIS_MATERIALIZATION"
    EVALUATION = "EVALUATION"
    FIXTURE_QUALIFICATION = "FIXTURE_QUALIFICATION"
    SCIENTIFIC_AUDIT = "SCIENTIFIC_AUDIT"
