from enum import StrEnum


class ConformanceErrorCode(StrEnum):
    SCHEMA_VALIDATION_ERROR = "SCHEMA_VALIDATION_ERROR"
    UNKNOWN_OBJECT_TYPE = "UNKNOWN_OBJECT_TYPE"
    DUPLICATE_OBJECT_TYPE = "DUPLICATE_OBJECT_TYPE"
    PRIMITIVE_OWNER_CONFLICT = "PRIMITIVE_OWNER_CONFLICT"
    INVALID_REFERENCE_KIND = "INVALID_REFERENCE_KIND"
    UNRESOLVED_LOGICAL_REFERENCE = "UNRESOLVED_LOGICAL_REFERENCE"
    REFERENCE_NOT_FOUND = "REFERENCE_NOT_FOUND"
    REFERENCE_HASH_MISMATCH = "REFERENCE_HASH_MISMATCH"
    INVALID_PARENT_REFERENCE = "INVALID_PARENT_REFERENCE"
    IMMUTABLE_OBJECT_MUTATION = "IMMUTABLE_OBJECT_MUTATION"
    OBJECT_TYPE_NOT_ELIGIBLE = "OBJECT_TYPE_NOT_ELIGIBLE"
    SNAPSHOT_ELIGIBILITY_VIOLATION = "SNAPSHOT_ELIGIBILITY_VIOLATION"
    INTERVENTION_TARGET_VIOLATION = "INTERVENTION_TARGET_VIOLATION"
    HEAD_CONFLICT = "HEAD_CONFLICT"
    SEMANTIC_CLOSURE_VIOLATION = "SEMANTIC_CLOSURE_VIOLATION"
    PROBE_ACTION_MISMATCH = "PROBE_ACTION_MISMATCH"
    PROBE_RESULT_REDIAGNOSIS_REQUIRED = "PROBE_RESULT_REDIAGNOSIS_REQUIRED"
    DIRECT_SYSTEM_LEARNING_WRITEBACK_FORBIDDEN = "DIRECT_SYSTEM_LEARNING_WRITEBACK_FORBIDDEN"
